name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build 1.17 project
        run: ./gradlew :bettersleeping-1.17:build --no-daemon --stacktrace

      - name: Build 1.19 project
        run: ./gradlew :bettersleeping-1.19:build --no-daemon --stacktrace

      # - name: Upload GitHub release
      #   uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: "**/build/libs/*.jar;!**/build/libs/*-sources.jar;!**/build/libs/*-dev.jar;!bettersleeping-core/"
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish 1.17 version
        uses: Kir-Antipov/mc-publish@v2.0
        with:
          modrinth-id: WRzU60Pt
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 552358
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: bettersleeping-1.17/build/libs/!(*-@(dev|sources)).jar

          name: BetterSleeping 0.6.0-beta.1 for 1.17+
          version: 0.6.0-beta.1+1.17
          version-type: beta

          loaders: |
            fabric

          game-versions: |
            1.17
            1.17.1
            1.18
            1.18.1
            1.18.2

      - name: Publish 1.19 version
        uses: Kir-Antipov/mc-publish@v2.0
        with:
          modrinth-id: WRzU60Pt
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 552358
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: bettersleeping-1.19/build/libs/!(*-@(dev|sources)).jar

          name: BetterSleeping 0.6.0-beta.1 for 1.19
          version: 0.6.0-beta.1+1.19
          version-type: beta

          loaders: |
            fabric

          game-versions: |
            22w19a
